# Generated by Django 3.2 on 2021-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uuid', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
