# Generated by Django 3.2 on 2021-07-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedfood',
            old_name='profile',
            new_name='buyer',
        ),
    ]
