# Generated by Django 3.2 on 2021-08-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_profile_selectedfood_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfood',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
