# Generated by Django 3.2 on 2021-07-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=5, unique=True)),
                ('food_name', models.CharField(max_length=150)),
                ('food_pictures', models.ImageField(upload_to='food_image')),
                ('food_description', models.TextField()),
                ('food_price', models.IntegerField()),
                ('food_type', models.CharField(choices=[('#1', 'Hamburger'), ('#2', 'Pizza'), ('#3', 'Other')], max_length=2)),
            ],
        ),
    ]
